name: main

on:
  - pull_request
  - push

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
        ocaml-version:
          - 4.11.0
          - 4.10.1
          - 4.09.1
          - 4.08.1
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Use OCaml ${{ matrix.ocaml-version }}
        uses: avsm/setup-ocaml@v1
        with:
          ocaml-version: ${{ matrix.ocaml-version }}
      - run: opam pin add ppx_serf.dev . --no-action
      - run: opam depext ppx_serf --yes --with-doc --with-test
      - run: opam install . --deps-only --with-doc --with-test
      - run: opam install lwt_ppx lwt_ssl
      - run: opam exec -- dune build @all @runtest
